import json
import os

# Categorized Word Banks and Texts
STANDARD_WORDS = [
    "the", "be", "of", "and", "a", "to", "in", "he", "have", "it", "that", "for", "they", "i", "with", "as", "not",
    "on", "she", "at", "by", "this", "we", "you", "do", "but", "from", "or", "which", "one", "would", "all", "will",
    "there", "say", "who", "make", "when", "can", "more", "if", "no", "man", "out", "other", "so", "what", "time",
    "up", "go", "about", "than", "into", "could", "state", "only", "new", "year", "some", "take", "come", "these",
    "know", "see", "use", "get", "like", "then", "first", "any", "work", "now", "may", "such", "give", "over", "think",
    "most", "even", "find", "day", "also", "after", "way", "many", "must", "look", "before", "great", "back", "through",
    "long", "where", "much", "should", "well", "people", "down", "own", "just", "because", "good", "each", "those",
    "feel", "seem", "how", "high", "too", "place", "little", "world", "very", "still", "nation", "hand", "old", "life",
    "tell", "write", "become", "here", "show", "house", "both", "between", "need", "mean", "call", "develop", "under",
    "last", "right", "move", "thing", "general", "school", "never", "same", "another", "begin", "while", "number",
    "part", "turn", "real", "leave", "might", "want", "point", "form", "off", "child", "few", "small", "since",
    "against", "ask", "late", "home", "interest", "large", "person", "end", "open", "public", "follow", "during",
    "present", "without", "again", "hold", "code", "cyber", "speed", "light", "quantum", "matrix", "focus", "system",
    "keyboard", "vector", "signal", "pulse", "stream", "fusion", "galaxy", "orbit", "pixel", "shadow", "future"
]

CODE_SNIPPETS = [
    "const calculateWPM = (chars, timeInSec) => Math.round((chars / 5) / (timeInSec / 60));",
    "function debounce(func, wait) { let timeout; return (...args) => { clearTimeout(timeout); timeout = setTimeout(() => func(...args), wait); }; }",
    "const numbers = [1, 2, 3, 4, 5]; const doubled = numbers.map(n => n * 2);",
    "async function fetchData(url) { const res = await fetch(url); return await res.json(); }",
    "document.addEventListener('keydown', (e) => { if (e.key === 'Tab') e.preventDefault(); });",
    "import React, { useState, useEffect } from 'react';",
    "export default function App() { return <div className='container'>Hello World</div>; }",
    "for (let i = 0; i < array.length; i++) { console.log(array[i]); }",
    "const isEven = (num) => num % 2 === 0;",
    "try { await processQueue(); } catch (err) { console.error('Queue failed:', err); }"
]

FAMOUS_QUOTES = [
    {
        "quote": "Do not go where the path may lead, go instead where there is no path and leave a trail.",
        "author": "Ralph Waldo Emerson"
    },
    {
        "quote": "The only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle.",
        "author": "Steve Jobs"
    },
    {
        "quote": "Success is not final, failure is not fatal: it is the courage to continue that counts.",
        "author": "Winston Churchill"
    },
    {
        "quote": "In the middle of difficulty lies opportunity.",
        "author": "Albert Einstein"
    },
    {
        "quote": "It is during our darkest moments that we must focus to see the light.",
        "author": "Aristotle"
    },
    {
        "quote": "Believe you can and you're halfway there.",
        "author": "Theodore Roosevelt"
    },
    {
        "quote": "Code is like humor. When you have to explain it, it's bad.",
        "author": "Cory House"
    },
    {
        "quote": "Simplicity is the soul of efficiency.",
        "author": "Austin Freeman"
    }
]

def generate_js_words_file():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    target_path = os.path.abspath(os.path.join(script_dir, "..", "webapp", "js", "words.js"))
    
    os.makedirs(os.path.dirname(target_path), exist_ok=True)
    
    js_content = f"""// Generated by execution/generate_texts.py
window.WORD_BANKS = {{
  standard: {json.dumps(STANDARD_WORDS, indent=2)},
  code: {json.dumps(CODE_SNIPPETS, indent=2)},
  quotes: {json.dumps(FAMOUS_QUOTES, indent=2)}
}};
"""
    with open(target_path, "w", encoding="utf-8") as f:
        f.write(js_content)
    
    print(f"Successfully generated wordbank at {target_path}")

if __name__ == "__main__":
    generate_js_words_file()
